blog/urls.py
# Core Django imports.
from django.urls import path

# Blog application imports.
from blog.views.blog.article_views import (
    ArticleListView,
    ArticleDetailView,
    ArticleSearchListView,
    TagArticlesListView,
)

from blog.views.blog.category_views import (
    CategoryArticlesListView,
    CategoriesListView,
    CategoryCreateView,
    CategoryUpdateCreateView,
)

from blog.views.blog.author_views import (
    AuthorArticlesListView,
    AuthorsListView,
)

from blog.views.blog.comment_views import (
    CommentCreateView,
    ArticleCommentList
)

from blog.views.dashboard.author.dashboard_views import (
    DashboardHomeView,
    ArticleWriteView,
    ArticleUpdateView,
    ArticleDeleteView,
    DashboardArticleDetailView,
    ArticlePublishView,
    AuthorWrittenArticlesView,
    AuthorPublishedArticlesView,
    AuthorDraftedArticlesView,
    AuthorDeletedArticlesView,
)

from blog.views.dashboard.author.author_profile_views import (
    AuthorProfileUpdateView,
    AuthorProfileView,
)

from blog.views.account.register_view import \
    (
      ActivateView,
      AccountActivationSentView,
      UserRegisterView,
    )
from blog.views.account.logout_view import UserLogoutView
from blog.views.account.login_view import UserLoginView


# Specifies the app name for name spacing.
app_name = "blog"

# article/urls.py
urlpatterns = [

    # ARTICLE URLS #

    # /home/
    path(
        route='',
        view=ArticleListView.as_view(),
        name='home'
    ),

    # /article/<str:slug>/
    path(
        route='@<str:username>/<str:slug>/',
        view=ArticleDetailView.as_view(),
        name='article_detail'

    ),

    # /search/?q=query/
    path(
        route='article/search/',
        view=ArticleSearchListView.as_view(),
        name='article_search_list_view'

     ),

    # /tag/<str:tag_name>/
    path(
        route='tag/<str:tag_name>/articles',
        view=TagArticlesListView.as_view(),
        name="tag_articles"
    ),


    # AUTHORS URLS #

    # /authors-list/
    path(
        route='authors/list/',
        view=AuthorsListView.as_view(),
        name='authors_list'
    ),

    # /author/<str:username>/
    path(
        route='author/<str:username>/articles',
        view=AuthorArticlesListView.as_view(),
        name='author_articles'
     ),


    # CATEGORY URLS #

    # category-articles/<str:slug>/
    path(
        route='category/<str:slug>/articles',
        view=CategoryArticlesListView.as_view(),
        name='category_articles'
    ),

    # /categories-list/
    path(
        route='categories/list/',
        view=CategoriesListView.as_view(),
        name='categories_list'
    ),

    # /category/new/
    path(
        route='category/create/',
        view=CategoryCreateView.as_view(),
        name="category_create"
    ),

    # /category/<str:slug>/update/
    path(
        route='category/<str:slug>/update/',
        view=CategoryUpdateCreateView.as_view(),
        name="category_update"
    ),




    # COMMENT URLS #

    # /comment/new/
    path(
        route='comment/new/<str:slug>/',
        view=CommentCreateView.as_view(),
        name="comment_create"
    ),

    # /<str:slug>/comments/
    path(
        route='<str:slug>/comments/',
        view=ArticleCommentList.as_view(),
        name="article_comments"
    ),


    # ACCOUNT URLS #

    # account/login/
    path(
        route='account/login/',
        view=UserLoginView.as_view(),
        name='login'
    ),

    # account/login/
    path(
        route='account/register/',
        view=UserRegisterView.as_view(),
        name='register'
    ),

    # account/logout/
    path(
        route='account/logout/',
        view=UserLogoutView.as_view(),
        name='logout'
    ),

    path(route='account_activation_sent/',
         view=AccountActivationSentView.as_view(),
         name='account_activation_sent'
         ),

    path(route='activate/<uidb64>/<token>/',
         view=ActivateView.as_view(),
         name='activate'
         ),



    # DASHBOARD URLS #

    # /author/dashboard/
    path(
        route="author/dashboard/home/",
        view=DashboardHomeView.as_view(),
        name="dashboard_home"
    ),

    # author/profile/details
    path(
        route='author/profile/details/',
        view=AuthorProfileView.as_view(),
        name='author_profile_details'
    ),

    # author/profile/update/
    path(
        route='author/profile/update/',
        view=AuthorProfileUpdateView.as_view(),
        name='author_profile_update'
    ),

    # me/article/write
    path(
        route='me/article/write/',
        view=ArticleWriteView.as_view(),
        name="article_write"
    ),

    # me/article/<str:slug>/update/
    path(
        route='me/article/<str:slug>/update/',
        view=ArticleUpdateView.as_view(),
        name="article_update"
    ),

    # /article/<str:slug>/delete/
    path(
        route='me/article/<str:slug>/delete/',
        view=ArticleDeleteView.as_view(),
        name="article_delete"
    ),

    # /me/<str:slug>/publish/
    path(
        route="article/<str:slug>/publish/",
        view=ArticlePublishView.as_view(),
        name="publish_article"
    ),

    # /me/articles/written/
    path(
        route="me/articles/written/",
        view=AuthorWrittenArticlesView.as_view(),
        name="written_articles"
    ),

    # /me/articles/published/
    path(
        route="me/articles/published/",
        view=AuthorPublishedArticlesView.as_view(),
        name="published_articles"
    ),

    # /me/articles/drafted/
    path(
        route="me/articles/drafts/",
        view=AuthorDraftedArticlesView.as_view(),
        name="drafted_articles"
    ),

    # /me/articles/deleted/
    path(
        route="me/articles/deleted/",
        view=AuthorDeletedArticlesView.as_view(),
        name="deleted_articles"
    ),

    # /me/<str:slug>/
    path(
        route="me/<str:slug>/",
        view=DashboardArticleDetailView.as_view(),
        name='dashboard_article_detail'

    ),

]

web_blog/urls.py
# Core Django imports
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),  # Urls for article app.
    path('api/v1/article/', include('blog.api.v1.routers.routers')), # Urls for API.
    path('admin/', admin.site.urls),

    # Url for password reset.
    path('account/password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'),
         name='password_reset'),

    # Url for successful password reset.
    path('account/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'),
         name='password_reset_done'),

    # Url for successful password reset confirm.
    path('account/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),

    # Url for password reset done.
    path('account/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns


# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "Web Admin"
admin.site.site_title = "Web Admin Portal"
admin.site.index_title = "Welcome to Web Blog Portal"

blog/models/article_models.py
# Core Django imports.
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

# Third party app imports
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField

# Blog application imports.
from blog.utils.blog_utils import count_words, read_time
from blog.models.category_models import Category


class Article(models.Model):

    # Article status constants
    DRAFTED = "DRAFTED"
    PUBLISHED = "PUBLISHED"

    # CHOICES
    STATUS_CHOICES = (
        (DRAFTED, 'Draft'),
        (PUBLISHED, 'Publish'),
    )

    # BLOG MODEL FIELDS
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='articles')
    title = models.CharField(max_length=250, null=False, blank=False)
    slug = models.SlugField()
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='articles')
    image = models.ImageField(default='article-default.jpg',
                              upload_to='article_pics')
    image_credit = models.CharField(max_length=250, null=True, blank=True)
    body = RichTextUploadingField(blank=True)
    tags = TaggableManager(blank=True)
    date_published = models.DateTimeField(null=True, blank=True,
                                          default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='DRAFT')
    views = models.PositiveIntegerField(default=0)
    count_words = models.CharField(max_length=50, default=0)
    read_time = models.CharField(max_length=50, default=0)
    deleted = models.BooleanField(default=False)

    class Meta:
        unique_together = ("title",)
        ordering = ('-date_published',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        self.count_words = count_words(self.body)
        self.read_time = read_time(self.body)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'username': self.author.username.lower(), 'slug': self.slug})

blog/models/author_models.py
# Core Django imports.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile-pic-default.jpg',
                              upload_to='profile_pics')
    banner_image = models.ImageField(default='slider-1.jpg',
                                     upload_to='banner')
    job_title = models.CharField(max_length=100)
    bio = models.CharField(max_length=100,
                           help_text="Short Bio (eg. I love cats and games)")

    address = models.CharField(max_length=100,
                               help_text="Enter Your Address"
                               )

    city = models.CharField(
                            max_length=100, help_text="Enter Your City"
                            )

    country = models.CharField(max_length=100,
                               help_text="Enter Your Country"
                               )

    zip_code = models.CharField(max_length=100,
                                help_text="Enter Your Zip Code"
                                )

    twitter_url = models.CharField(max_length=250, default="#",
                                   blank=True, null=True,
                                   help_text=
                                   "Enter # if you don't have an account")
    instagram_url = models.CharField(max_length=250, default="#",
                                     blank=True, null=True,
                                     help_text=
                                     "Enter # if you don't have an account")
    facebook_url = models.CharField(max_length=250, default="#",
                                    blank=True, null=True,
                                    help_text=
                                    "Enter # if you don't have an account")
    github_url = models.CharField(max_length=250, default="#",
                                  blank=True, null=True,
                                  help_text=
                                  "Enter # if you don't have an account")

    email_confirmed = models.BooleanField(default=False)

    created_on = models.DateTimeField(default=timezone.now)

    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

blog/models/category_models.py
# Core Django imports.
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):

    name = models.CharField(max_length=100, null=False, blank=False)
    slug = models.SlugField()
    image = models.ImageField(default='category-default.jpg',
                              upload_to='category_images')
    approved = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:category_articles',
                       kwargs={'slug': self.slug})

blog/models/comment_models.py
# Core Django imports.
from django.db import models
from django.utils import timezone

# Blog application imports.
from blog.models.article_models import Article


class Comment(models.Model):

    name = models.CharField(max_length=250, null=False, blank=False)
    email = models.EmailField()
    comment = models.TextField(null=False, blank=False)
    article = models.ForeignKey(Article, on_delete=models.CASCADE,
                                related_name='comments')
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.article}"

blog/api/v1/views/article_views.py
# Third-party apps import
from rest_framework import generics

# Blog app imports
from blog.models.article_models import Article
from ..serializers.article_serializers import ArticleSerializer


class ArticleList(generics.ListAPIView):
    queryset = Article.objects.filter(status='PUBLISHED')
    serializer_class = ArticleSerializer


class CategoryArticleList(generics.ListAPIView):
    serializer_class = ArticleSerializer

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        articles = Article.objects.filter(category__name=category_name,
                                          status='PUBLISHED'
                                          )
        return articles

blog/api/v1/views/category_views.py
# Third-party apps import
from rest_framework import generics

# Local application imports
from blog.models.article_models import Category
from ..serializers.category_serializers import CategorySerializer


class CategoryList(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

blog/templates/blog/article/article_detail.html
{% extends 'blog/blog_base.html' %}
{% load static %}
'
{% block stylesheet %}
    {{ block.super }}
     <link href="{% static 'blog/css/web/detail-page.css' %}" rel="stylesheet" />

{% endblock stylesheet %}


{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
	<div class="slider" style="height: 400px; width: 100%;
    background-image: url({{ article.category.image.url }});
    background-size: contain" >
	</div><!-- slider -->

	<section class="post-area">
		<div class="container">

			<div class="row">

				<div class="col-lg-1 col-md-0"></div>
				<div class="col-lg-10 col-md-12">

					<figure class="main-post">

						<div class="post-top-area">

							<h5 class="pre-title"><b>{{ article.category }}</b></h5>

							<h3 class="title"><b>{{ article.title }}</b></h3>

							<div class="post-info">

								<div class="left-area">
									<a class="avatar" href="{% url 'blog:author_articles' article.author.username %}">
                                        <img src="{{ article.author.profile.image.url }}" alt="Profile Image" class="article-author-profile-image"></a>
								</div>

								<div class="middle-area">
									By <a class="name" href="{% url 'blog:author_articles' article.author.username %}">
                                        <b>{{ article.author.username }}</b></a>
									<h6 class="date">on {{ article.date_published.date }}</h6>
								</div>

							</div><!-- post-info -->
                           <div class="post-icons-area">
								<ul class="post-icons">
                                    <li><a><i class="ion-ios-paper"></i>{{ article.count_words }} word{{ article.count_words|pluralize }}</a></li>
									<li><a><i class="ion-ios-clock"></i>{{ article.read_time }} min{{ article.read_time|pluralize }} read</a></li>
									<li><a><i class="ion-chatbubbles"></i>{{ article.comments.count }} comment{{ article.comments.count|pluralize }}</a></li>
									<li><a><i class="ion-eye"></i>{{ article.views }} view{{ article.views|pluralize }}</a></li>
								</ul>

								<ul class="icons">
									<li>SHARE : </li>
                                    <li>
                                        <a href="mailto:?subject={{ article.title }}&amp;body=Check out this article {{ request.build_absolute_uri }}" target="_blank">
                                        <i class="ion-android-mail"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.linkedin.com/sharing/share-offsite/?url={{ request.build_absolute_uri }}"  target="_blank">
                                        <i class="ion-social-linkedin"></i>
                                        </a>
                                    </li>
									<li>
                                        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">
                                        <i class="ion-social-facebook"></i>
                                        </a>
                                    </li>
									<li>
                                        <a href="http://twitter.com/share?text={{ article.title }}. &url={{ request.build_absolute_uri }}" target="_blank">
                                        <i class="ion-social-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://api.whatsapp.com/send?text={{ request.build_absolute_uri }}" target="_blank">
                                            <i class="ion-social-whatsapp"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://telegram.me/share/url?url={{ request.build_absolute_uri }}&text={{ article.title }}" target="_blank">
                                            <i class="fa fa-telegram"></i>
                                        </a>
                                    </li>
								</ul>
							</div>

						</div><!-- post-top-area -->

						<figure class="post-image"><img class="article-image" src="{{ article.image.url }}" alt="Blog Image">
				       {% if article.image_credit %}
                           <figcaption class="mt-2 text-center image-caption">
                            (Image Credit: {{ article.image_credit}})
                        </figcaption>
                       {% endif %}
                        </figure>

						<div class="post-bottom-area">

                        <!-- article body -->
                            <p class="para">{{ article.body | safe }}</p>

                        <!-- tags -->
							<ul class="tags">
                                {% for tag in article.tags.all %}
								<li><a href="{% url 'blog:tag_articles' tag_name=tag.name %}">{{ tag.name }}</a></li>
                                {% endfor %}
							</ul>

						</div><!-- post-bottom-area -->
                    </figure>
					</div><!-- main-post -->
				</div><!-- col-lg-8 col-md-12 -->
			</div><!-- row -->
		</div><!-- container -->
	</section><!-- post-area -->


	<section class="recomended-area section">
		<div class="container">
        <h4><b>RELATED ARTICLES</b></h4>
             {% if related_articles %}
			<div class="row">
            {% for related_article in related_articles %}
				<div class="col-lg-4 col-md-6">
					<div class="card h-100">
						<div class="single-post post-style-1">

							<div class="blog-image">
                                <img src="{{ related_article.image.url }}"
                                     width="330" height="220"
                                     alt="Blog Image">
                            </div>

							<a class="avatar" href="{% url 'blog:author_articles' related_article.author.username %}">
                                <img class="profile-image" src="{{ related_article.author.profile.image.url }}" alt="Profile Image"></a>

							<div class="blog-info">

								<h4 class="title"><a href="{{ related_article.get_absolute_url }}">
                                    <b>{{ related_article.title }}</b></a></h4>

								<ul class="post-footer">
									<li><i class="ion-ios-clock"></i>{{ article.read_time }} min read</li>
									<li><i class="ion-chatbubble"></i>{{ article.comments.count }}</li>
									<li><i class="ion-eye"></i>{{ article.views }}</li>
								</ul>

							</div><!-- article-info -->
						</div><!-- single-post -->
					</div><!-- card -->
				</div><!-- col-md-6 col-sm-12 -->
             {% endfor %}
			</div><!-- row -->
             {% else %}
                <div class="alert alert-warning"><b>No Related Articles</b></div>
            {% endif %}
		</div><!-- container -->
	</section>

	<section class="comment-section center-text">
		<div class="container">
			<h4><b>POST COMMENT</b></h4>
			<div class="row">

				<div class="col-lg-2 col-md-0"></div>

				<div class="col-lg-8 col-md-12">
					<div class="comment-form">
						<form method="post" action="{% url 'blog:comment_create' article.slug %}">
                            {% csrf_token %}
							<div class="row">
								<div class="col-sm-6">
									{{ comment_form.name }}
								</div><!-- col-sm-6 -->
								<div class="col-sm-6">
									{{ comment_form.email }}
								</div><!-- col-sm-6 -->

								<div class="col-sm-12">
                                    {{ comment_form.comment }}
								</div><!-- col-sm-12 -->
								<div class="col-sm-12">
									<button class="submit-btn" type="submit" id="form-submit"><b>POST COMMENT</b></button>
								</div><!-- col-sm-12 -->

							</div><!-- row -->
						</form>
					</div><!-- comment-form -->


                    <a class="more-comment-btn" href="{% url 'blog:article_comments' article.slug %}">
                        <b>SEE COMMENTS ({{ article.comments.count }})</b></a>

				</div><!-- col-lg-8 col-md-12 -->


			</div><!-- row -->

		</div><!-- container -->
	</section>
{% endblock content %}

blog/templates/blog/article/article_search_list.html
{% extends 'blog/blog_base.html' %}

{% block title %}
 Search Results
{% endblock title %}

{% block messages %}
{% endblock messages %}

{% block content %}
    {% if categories %}
    <div class="main-slider">
		<div class="swiper-container position-static" data-slide-effect="slide" data-autoheight="false"
			data-swiper-speed="500" data-swiper-autoplay="5000" data-swiper-margin="0" data-swiper-slides-per-view="4"
			data-swiper-breakpoints="true" data-swiper-loop="true" >
			<div class="swiper-wrapper">
                {% for category in categories %}
				<div class="swiper-slide">
					<a class="slider-category" href="{{ category.get_absolute_url }}">
						<div class="category-image">
                            <img src="{{ category.image.url }}"
                                 class="category-image"
                                 width="352" height="235"
                                 alt="Blog Image">
                        </div>

						<div class="category">
							<div class="display-table center-text">
								<div class="display-table-cell">
									<h3><b>{{ category.name }}</b></h3>
								</div>
							</div>
						</div>
					</a>
				</div><!-- swiper-slide -->
                {% endfor %}

			</div><!-- swiper-wrapper -->
		</div><!-- swiper-container -->

	</div><!-- slider -->
    {% else %}
        <center><div class="alert alert-warning"><b>No Categories</b></div></center>
    {% endif %}

	<section class="blog-area section">
		<div class="container">
            <!-- Messages -->
           <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                      <div class="text-center font-weight-bold alert
                           {% if message.level_tag == 'error' %}
                           alert-danger
                           {% else %}
                           alert-{{ message.tags }}
                           {% endif %}">

                        {{ message }}
                      </div>
                    {% endfor %}
              {% endif %}
            </div>
          </div>


            <!-- Results -->
            {% if search_results %}
			<div class="row">
                {% for article in search_results %}
				<div class="col-lg-4 col-md-6">
					<div class="card h-100">
						<div class="single-post post-style-1">

							<div class="blog-image">
                                <img src="{{ article.image.url }}"
                                     width="330" height="220"
                                     alt="Blog Image"
                                >
                            </div>

							<a class="avatar" href="{% url 'blog:author_articles' article.author.username %}">
                                <img src="{{ article.author.profile.image.url }}" alt="Profile Image"
                                     class="profile-image">
                            </a>

							<div class="blog-info">

								<h4 class="title"><a href="{{ article.get_absolute_url }}"><b>{{ article.title }}</b></a></h4>

								<ul class="post-footer">
									<li><a><i class="ion-ios-clock"></i>{{ article.read_time }} min{{ article.read_time|pluralize }} read</a></li>
									<li><i class="ion-chatbubbles"></i>{{ article.comments.count }}</li>
									<li><i class="ion-eye"></i>{{ article.views }}</li>
								</ul>

							</div><!-- article-info -->
						</div><!-- single-post -->
					</div><!-- card -->
				</div><!-- col-lg-4 col-md-6 -->
                {% endfor %}
			</div><!-- row -->
            {% endif %}
                {# Pagination for article post #}
            {% if is_paginated %}

                {# Displays previous pages #}
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-info mb-4"
                       href="?page={{ page_obj.previous_page_number }}">Previous
                    </a>
                {% endif %}

                {# Displays current page #}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                 {% endfor %}

                {# Displays next pages #}
               {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4"
                       href="?page={{ page_obj.next_page_number }}">Next
                    </a>
                    <a class="btn btn-outline-info mb-4"
                       href="?page={{ page_obj.paginator.num_pages }}">Last
                    </a>
                {% endif %}

            {% endif %}

		</div><!-- container -->
	</section><!-- section -->
{% endblock content %}