blog/urls.py
# Core Django imports.
from django.urls import path

# Blog application imports.
from blog.views.blog.article_views import (
    ArticleListView,
    ArticleDetailView,
    ArticleSearchListView,
    TagArticlesListView,
)

from blog.views.blog.category_views import (
    CategoryArticlesListView,
    CategoriesListView,
    CategoryCreateView,
    CategoryUpdateCreateView,
)

from blog.views.blog.author_views import (
    AuthorArticlesListView,
    AuthorsListView,
)

from blog.views.blog.comment_views import (
    CommentCreateView,
    ArticleCommentList
)

from blog.views.dashboard.author.dashboard_views import (
    DashboardHomeView,
    ArticleWriteView,
    ArticleUpdateView,
    ArticleDeleteView,
    DashboardArticleDetailView,
    ArticlePublishView,
    AuthorWrittenArticlesView,
    AuthorPublishedArticlesView,
    AuthorDraftedArticlesView,
    AuthorDeletedArticlesView,
)

from blog.views.dashboard.author.author_profile_views import (
    AuthorProfileUpdateView,
    AuthorProfileView,
)

from blog.views.account.register_view import \
    (
      ActivateView,
      AccountActivationSentView,
      UserRegisterView,
    )
from blog.views.account.logout_view import UserLogoutView
from blog.views.account.login_view import UserLoginView


# Specifies the app name for name spacing.
app_name = "blog"

# article/urls.py
urlpatterns = [

    # ARTICLE URLS #

    # /home/
    path(
        route='',
        view=ArticleListView.as_view(),
        name='home'
    ),

    # /article/<str:slug>/
    path(
        route='@<str:username>/<str:slug>/',
        view=ArticleDetailView.as_view(),
        name='article_detail'

    ),

    # /search/?q=query/
    path(
        route='article/search/',
        view=ArticleSearchListView.as_view(),
        name='article_search_list_view'

     ),

    # /tag/<str:tag_name>/
    path(
        route='tag/<str:tag_name>/articles',
        view=TagArticlesListView.as_view(),
        name="tag_articles"
    ),


    # AUTHORS URLS #

    # /authors-list/
    path(
        route='authors/list/',
        view=AuthorsListView.as_view(),
        name='authors_list'
    ),

    # /author/<str:username>/
    path(
        route='author/<str:username>/articles',
        view=AuthorArticlesListView.as_view(),
        name='author_articles'
     ),


    # CATEGORY URLS #

    # category-articles/<str:slug>/
    path(
        route='category/<str:slug>/articles',
        view=CategoryArticlesListView.as_view(),
        name='category_articles'
    ),

    # /categories-list/
    path(
        route='categories/list/',
        view=CategoriesListView.as_view(),
        name='categories_list'
    ),

    # /category/new/
    path(
        route='category/create/',
        view=CategoryCreateView.as_view(),
        name="category_create"
    ),

    # /category/<str:slug>/update/
    path(
        route='category/<str:slug>/update/',
        view=CategoryUpdateCreateView.as_view(),
        name="category_update"
    ),




    # COMMENT URLS #

    # /comment/new/
    path(
        route='comment/new/<str:slug>/',
        view=CommentCreateView.as_view(),
        name="comment_create"
    ),

    # /<str:slug>/comments/
    path(
        route='<str:slug>/comments/',
        view=ArticleCommentList.as_view(),
        name="article_comments"
    ),


    # ACCOUNT URLS #

    # account/login/
    path(
        route='account/login/',
        view=UserLoginView.as_view(),
        name='login'
    ),

    # account/login/
    path(
        route='account/register/',
        view=UserRegisterView.as_view(),
        name='register'
    ),

    # account/logout/
    path(
        route='account/logout/',
        view=UserLogoutView.as_view(),
        name='logout'
    ),

    path(route='account_activation_sent/',
         view=AccountActivationSentView.as_view(),
         name='account_activation_sent'
         ),

    path(route='activate/<uidb64>/<token>/',
         view=ActivateView.as_view(),
         name='activate'
         ),



    # DASHBOARD URLS #

    # /author/dashboard/
    path(
        route="author/dashboard/home/",
        view=DashboardHomeView.as_view(),
        name="dashboard_home"
    ),

    # author/profile/details
    path(
        route='author/profile/details/',
        view=AuthorProfileView.as_view(),
        name='author_profile_details'
    ),

    # author/profile/update/
    path(
        route='author/profile/update/',
        view=AuthorProfileUpdateView.as_view(),
        name='author_profile_update'
    ),

    # me/article/write
    path(
        route='me/article/write/',
        view=ArticleWriteView.as_view(),
        name="article_write"
    ),

    # me/article/<str:slug>/update/
    path(
        route='me/article/<str:slug>/update/',
        view=ArticleUpdateView.as_view(),
        name="article_update"
    ),

    # /article/<str:slug>/delete/
    path(
        route='me/article/<str:slug>/delete/',
        view=ArticleDeleteView.as_view(),
        name="article_delete"
    ),

    # /me/<str:slug>/publish/
    path(
        route="article/<str:slug>/publish/",
        view=ArticlePublishView.as_view(),
        name="publish_article"
    ),

    # /me/articles/written/
    path(
        route="me/articles/written/",
        view=AuthorWrittenArticlesView.as_view(),
        name="written_articles"
    ),

    # /me/articles/published/
    path(
        route="me/articles/published/",
        view=AuthorPublishedArticlesView.as_view(),
        name="published_articles"
    ),

    # /me/articles/drafted/
    path(
        route="me/articles/drafts/",
        view=AuthorDraftedArticlesView.as_view(),
        name="drafted_articles"
    ),

    # /me/articles/deleted/
    path(
        route="me/articles/deleted/",
        view=AuthorDeletedArticlesView.as_view(),
        name="deleted_articles"
    ),

    # /me/<str:slug>/
    path(
        route="me/<str:slug>/",
        view=DashboardArticleDetailView.as_view(),
        name='dashboard_article_detail'

    ),

]

web_blog/urls.py
# Core Django imports
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),  # Urls for article app.
    path('api/v1/article/', include('blog.api.v1.routers.routers')), # Urls for API.
    path('admin/', admin.site.urls),

    # Url for password reset.
    path('account/password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'),
         name='password_reset'),

    # Url for successful password reset.
    path('account/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'),
         name='password_reset_done'),

    # Url for successful password reset confirm.
    path('account/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),

    # Url for password reset done.
    path('account/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns


# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "Web Admin"
admin.site.site_title = "Web Admin Portal"
admin.site.index_title = "Welcome to Web Blog Portal"

blog/models/article_models.py
# Core Django imports.
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

# Third party app imports
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField

# Blog application imports.
from blog.utils.blog_utils import count_words, read_time
from blog.models.category_models import Category


class Article(models.Model):

    # Article status constants
    DRAFTED = "DRAFTED"
    PUBLISHED = "PUBLISHED"

    # CHOICES
    STATUS_CHOICES = (
        (DRAFTED, 'Draft'),
        (PUBLISHED, 'Publish'),
    )

    # BLOG MODEL FIELDS
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='articles')
    title = models.CharField(max_length=250, null=False, blank=False)
    slug = models.SlugField()
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='articles')
    image = models.ImageField(default='article-default.jpg',
                              upload_to='article_pics')
    image_credit = models.CharField(max_length=250, null=True, blank=True)
    body = RichTextUploadingField(blank=True)
    tags = TaggableManager(blank=True)
    date_published = models.DateTimeField(null=True, blank=True,
                                          default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='DRAFT')
    views = models.PositiveIntegerField(default=0)
    count_words = models.CharField(max_length=50, default=0)
    read_time = models.CharField(max_length=50, default=0)
    deleted = models.BooleanField(default=False)

    class Meta:
        unique_together = ("title",)
        ordering = ('-date_published',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        self.count_words = count_words(self.body)
        self.read_time = read_time(self.body)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'username': self.author.username.lower(), 'slug': self.slug})

blog/models/author_models.py
# Core Django imports.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile-pic-default.jpg',
                              upload_to='profile_pics')
    banner_image = models.ImageField(default='slider-1.jpg',
                                     upload_to='banner')
    job_title = models.CharField(max_length=100)
    bio = models.CharField(max_length=100,
                           help_text="Short Bio (eg. I love cats and games)")

    address = models.CharField(max_length=100,
                               help_text="Enter Your Address"
                               )

    city = models.CharField(
                            max_length=100, help_text="Enter Your City"
                            )

    country = models.CharField(max_length=100,
                               help_text="Enter Your Country"
                               )

    zip_code = models.CharField(max_length=100,
                                help_text="Enter Your Zip Code"
                                )

    twitter_url = models.CharField(max_length=250, default="#",
                                   blank=True, null=True,
                                   help_text=
                                   "Enter # if you don't have an account")
    instagram_url = models.CharField(max_length=250, default="#",
                                     blank=True, null=True,
                                     help_text=
                                     "Enter # if you don't have an account")
    facebook_url = models.CharField(max_length=250, default="#",
                                    blank=True, null=True,
                                    help_text=
                                    "Enter # if you don't have an account")
    github_url = models.CharField(max_length=250, default="#",
                                  blank=True, null=True,
                                  help_text=
                                  "Enter # if you don't have an account")

    email_confirmed = models.BooleanField(default=False)

    created_on = models.DateTimeField(default=timezone.now)

    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

blog/models/category_models.py
# Core Django imports.
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):

    name = models.CharField(max_length=100, null=False, blank=False)
    slug = models.SlugField()
    image = models.ImageField(default='category-default.jpg',
                              upload_to='category_images')
    approved = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:category_articles',
                       kwargs={'slug': self.slug})

blog/models/comment_models.py
# Core Django imports.
from django.db import models
from django.utils import timezone

# Blog application imports.
from blog.models.article_models import Article


class Comment(models.Model):

    name = models.CharField(max_length=250, null=False, blank=False)
    email = models.EmailField()
    comment = models.TextField(null=False, blank=False)
    article = models.ForeignKey(Article, on_delete=models.CASCADE,
                                related_name='comments')
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.article}"

blog/api/v1/views/article_views.py
# Third-party apps import
from rest_framework import generics

# Blog app imports
from blog.models.article_models import Article
from ..serializers.article_serializers import ArticleSerializer


class ArticleList(generics.ListAPIView):
    queryset = Article.objects.filter(status='PUBLISHED')
    serializer_class = ArticleSerializer


class CategoryArticleList(generics.ListAPIView):
    serializer_class = ArticleSerializer

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        articles = Article.objects.filter(category__name=category_name,
                                          status='PUBLISHED'
                                          )
        return articles

blog/api/v1/views/category_views.py
# Third-party apps import
from rest_framework import generics

# Local application imports
from blog.models.article_models import Category
from ..serializers.category_serializers import CategorySerializer


class CategoryList(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

blog/templates/blog/blog_base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>

    <!-- Favicon-->
    <link rel="icon" href="{% static 'blog/images/favicon.png' %}"
          type="image/gif" sizes="16x16">

    <!-- Meta Tags -->
    <meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Olena>
    <meta name="keywords" content="Blog, Django-Blog, Django-app">

    <!-- Title -->
    <title>WEB | {% block title %}{% endblock title %}</title>

	<!-- Font and Font-awesome -->
    <link href="{% static 'blog/css/common-css/fontawesome-free/css/all.min.css' %}"
          rel="stylesheet"  type="text/css" />
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"
          rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet">

    <!-- Stylesheets -->
	{% block stylesheet %}
       <!-- Bootstrap select -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.10/dist/css/bootstrap-select.min.css">
	<link href="{% static 'blog/css/common-css/bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/common-css/swiper.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/common-css/ionicons.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/web/styles.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/web/responsive.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'dashboard/author/css/prism.css' %}">

    {% endblock stylesheet %}

</head>
<body >

	<header>
		<div class="container-fluid position-relative no-side-padding">

			<a href="{% url 'blog:home' %}" class="logo">
                <img src="{% static 'blog/images/logo.png' %}" alt="Logo Image"></a>

			<div class="menu-nav-icon" data-nav-menu="#main-menu"><i class="ion-navicon"></i></div>

			<ul class="main-menu visible-on-click" id="main-menu">
{#				<li><a href="{% url 'blog:authors_list' %}">Authors</a></li>#}
				<li><a href="{% url 'blog:categories_list' %}">Categories</a></li>
                <li><a href="#">About</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'blog:dashboard_home' %}">Dashboard</a></li>
                    <li><a href="{% url 'blog:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'blog:login' %}">Login</a></li>
                {% endif %}
			</ul><!-- main-menu -->

			<div class="src-area">
				<form method="get" action="{% url 'blog:article_search_list_view' %}">
					<button class="src-btn" type="submit"><i class="ion-ios-search-strong"></i></button>
					<input class="src-input" type="text" name="q" placeholder="Search for Articles">
				</form>
			</div>
		</div><!-- conatiner -->
	</header>


   <!-- Messages -->
      {% block messages %}
       <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                  <div class="text-center font-weight-bold alert alert-dismissible fade show
                       {% if message.level_tag == 'error' %}
                       alert-danger
                       {% else %}
                       alert-{{ message.tags }}
                       {% endif %}">
                    {{ message }}
                     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                     </button>
                  </div>
                {% endfor %}
              {% endif %}
        </div>
      </div>
      {% endblock messages %}

    {% block content %}
    {% endblock content %}


{#    {% block footer %}#}
{##}
{#        <footer>#}
{##}
{#		<div class="container">#}
{#			<div class="row">#}
{##}
{#				<div class="col-lg-4 col-md-6">#}
{#					<div class="footer-section">#}
{##}
{#						<a class="logo" href="#">#}
{#                            <img src="{% static 'blog/images/logo.png' %}"#}
{#                                 alt="Logo Image"></a>#}
{#						<p class="copyright">WEB</p>#}
{##}
{#						<ul class="icons">#}
{#							<li><a href="#">#}
{#                                <i class="ion-social-facebook-outline"></i>#}
{#                               </a>#}
{#                            </li>#}
{#							<li><a href="#">#}
{#                                <i class="ion-social-twitter-outline">#}
{#                                </i>#}
{#                                </a>#}
{#                            </li>#}
{#							<li><a href="#">#}
{#                                <i class="ion-social-instagram-outline">#}
{#                                </i>#}
{#                                </a>#}
{#                            </li>#}
{#							<li><a href="#">#}
{#                                <i class="ion-social-vimeo-outline">#}
{#                                </i>#}
{#                                </a>#}
{#                            </li>#}
{#							<li><a href="#">#}
{#                                <i class="ion-social-pinterest-outline"></i>#}
{#                                </a>#}
{#                            </li>#}
{#						</ul>#}
{##}
{#					</div><!-- footer-section -->#}
{#				</div><!-- col-lg-4 col-md-6 -->#}
{##}
{#				<div class="col-lg-4 col-md-6">#}
{#						<div class="footer-section">#}
{#						<h4 class="title"><b>MENU</b></h4>#}
{#						<ul>#}
{#							<li><a href="{% url 'blog:login' %}">Login</a></li>#}
{#							<li><a href="#">HEALTH</a></li>#}
{#							<li><a href="#">MUSIC</a></li>#}
{#						</ul>#}
{#						<ul>#}
{#                            <li><a href="{% url 'blog:register' %}">Sign Up</a></li>#}
{#							<li><a href="#">DESIGN</a></li>#}
{#							<li><a href="#">TRAVEL</a></li>#}
{#						</ul>#}
{#					</div><!-- footer-section -->#}
{#				</div><!-- col-lg-4 col-md-6 -->#}
{##}
{#				<div class="col-lg-4 col-md-6">#}
{#					<div class="footer-section">#}
{##}
{#						<h4 class="title"><b>SUBSCRIBE</b></h4>#}
{#						<div class="input-area">#}
{#							<form>#}
{#								<input class="email-input" type="text"#}
{#                                       placeholder="Enter your email">#}
{#								<button class="submit-btn" type="submit">#}
{#                                    <i class="icon ion-ios-email-outline"></i>#}
{#                                </button>#}
{#							</form>#}
{#						</div>#}
{##}
{#					</div><!-- footer-section -->#}
{#				</div><!-- col-lg-4 col-md-6 -->#}
{##}
{#			</div><!-- row -->#}
{#		</div><!-- container -->#}
{#	</footer>#}
{##}
{# {% endblock footer %}#}

    <!-- SCRIPTS -->
 {% block scripts %}

	<script src="{% static 'blog/js/common-js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'blog/js/common-js/tether.min.js' %}"></script>
	<script src="{% static 'blog/js/common-js/bootstrap.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'blog/js/common-js/swiper.js' %}"></script>
	<script src="{% static 'blog/js/common-js/scripts.js' %}"></script>
     <script src="{% static 'blog/js/blog/prism.js' %}"></script>

 {% endblock scripts %}
</body>
</html>